# To run you need to add an entry on your etc hosts file to map localhost.jaqpot.org to 127.0.0.1

services:
  postgres:
    network_mode: 'host'
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: jaqpot
      POSTGRES_PASSWORD: jaqpot
    #    ports:
    #      - '5432:5432'
    volumes:
      - ./etc/init-db-scripts:/docker-entrypoint-initdb.d
      - ./docker/db:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  keycloak:
    depends_on: [ postgres ]
    restart: always
    network_mode: 'host'
    image: quay.io/keycloak/keycloak:24.0.3
    command:
      - "start-dev"
      - "--http-port=8070"
      - "--import-realm"
      - "-Djava.net.preferIPv4Stack=true"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: jaqpot
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://localhost.jaqpot.org:5432/keycloak
      KC_DB_USERNAME: jaqpot
      KC_DB_PASSWORD: jaqpot
      JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    volumes:
      - ./docker/keycloak/imports:/opt/keycloak/data/import
  #    ports:

  r-inference:
    image: upcintua/jpdi-r:1.1.9
    ports:
      - "8004:8004"

  python-generic-22:
    #    network_mode: 'host'
    image: euclia/jaqpot-python-generic:0.22
    ports:
      - 8822:8002

  python-generic-23:
    #    network_mode: 'host'
    image: euclia/jaqpot-python-generic:0.23.1
    ports:
      - 8823:8002


  python-generic-24:
    #    network_mode: 'host'
    image: euclia/jaqpot-python-generic:0.24.1
    ports:
      - 8824:8002
