# To run you need to add an entry on your etc hosts file to map localhost.jaqpot.org to 127.0.0.1

services:
  postgres:
    network_mode: 'host'
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: jaqpot
      POSTGRES_PASSWORD: jaqpot
    #    ports:
    #      - '5432:5432'
    volumes:
      - ./etc/init-db-scripts:/docker-entrypoint-initdb.d
      - ./docker/db:/var/lib/postgresql/data

  keycloak:
    depends_on: [ postgres ]
    restart: always
    network_mode: 'host'
    image: quay.io/keycloak/keycloak:24.0.3
    command:
      - "start-dev"
      - "--http-port=8070"
      - "--import-realm"
      - "-Djava.net.preferIPv4Stack=true"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: jaqpot
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://localhost.jaqpot.org:5432/keycloak
      KC_DB_USERNAME: jaqpot
      KC_DB_PASSWORD: jaqpot
      JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    volumes:
      - ./docker/keycloak/imports:/opt/keycloak/data/import
  #    ports:
