spring:
  application:
    name: jaqpot-api
  datasource:
    url: jdbc:postgresql://localhost.jaqpot.org:5432/jaqpot
    username: jaqpot
    password: jaqpot
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost.jaqpot.org:8070/realms/jaqpot-local
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host:
    port: 587
    username:
    password:
    from: info@jaqpot.org
    reply-to:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  docker:
    compose:
      lifecycle-management: none
#  cache:
#    type: none

springdoc:
  paths-to-match: /v1/models/**, /v1/organizations/**, /v1/user/**
  paths-to-exclude: /v1/organizations/*/invitations/**, /v1/user/settings

management:
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

aws:
  region: eu-west-1
  s3:
    models-bucket:
    datasets-bucket:
    doas-bucket:
    preprocessors-bucket:
    user-avatars-bucket:

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

keycloak:
  client-id: admin-cli
  client-secret: 62r8Qm79gjwtA6wFMYt41InUK718nwzJ
  realm: jaqpot-local
  server-url: http://localhost.jaqpot.org:8070
  impersonation-client-id: impersonator
  impersonation-client-secret: NrKN1ayoM4Obaz1m3tKNizWFKWGw6gZZ

jaqpot:
  model:
    max-input-prediction-rows: 100
  frontend:
    url: http://localhost.jaqpot.org:3000
  runtime:
    jaqpotpy-inference-v6: http://localhost.jaqpot.org:8002
    jaqpotr: http://localhost.jaqpot.org:8004

    legacy:
      jaqpot-inference: http://localhost.jaqpot.org:8880
      generic-python-020: http://localhost.jaqpot.org:8820
      generic-python-022: http://localhost.jaqpot.org:8822
      generic-python-023: http://localhost.jaqpot.org:8823
      generic-python-024: http://localhost.jaqpot.org:8824
      generic-python-1: http://localhost.jaqpot.org:8825
  qsartoolbox:
    url:



