spring:
  application:
    name: jaqpot-api
  datasource:
    url: jdbc:postgresql://localhost.jaqpot.org:5432/jaqpot
    username: jaqpot
    password: jaqpot
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost.jaqpot.org:8070/realms/jaqpot-local
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host:
    port: 587
    username:
    password:
    from: info@jaqpot.org
    reply-to:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  docker:
    compose:
      lifecycle-management: none

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

keycloak:
  client-id: admin-cli
  client-secret: 62r8Qm79gjwtA6wFMYt41InUK718nwzJ
  realm: jaqpot-local
  server-url: http://localhost.jaqpot.org:8070

jaqpot:
  frontend:
    url: http://localhost.jaqpot.org:3000
  runtime:
    jaqpotpy-inference-v6: http://localhost.jaqpot.org:8002/predict/
    jaqpotpy-inference-legacy-22: http://localhost.jaqpot.org:8822/predict/sklearn/
    jaqpotpy-inference-legacy-23: http://localhost.jaqpot.org:8823/predict/sklearn/
    jaqpotpy-inference-legacy-24: http://localhost.jaqpot.org:8824/predict/sklearn/
    jaqpotr: http://localhost.jaqpot.org:8004



