spring:
  application:
    name: jaqpot-api
  datasource:
    url: jdbc:postgresql://localhost:5432/jaqpot
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/jaqpot-local

