CREATE SEQUENCE IF NOT EXISTS model_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE model
(
    id         INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_public  BOOLEAN NOT NULL,
    CONSTRAINT pk_model PRIMARY KEY (id)
);

