ALTER TABLE feature
    DROP CONSTRAINT FK_FEATURE_ON_MODEL;
ALTER TABLE feature
    ADD CONSTRAINT FK_FEATURE_ON_MODEL FOREIGN KEY (model_id) REFERENCES model (id) ON DELETE CASCADE;

ALTER TABLE library
    DROP CONSTRAINT FK_LIBRARY_ON_MODEL;
ALTER TABLE library
    ADD CONSTRAINT FK_LIBRARY_ON_MODEL FOREIGN KEY (model_id) REFERENCES model (id) ON DELETE CASCADE;

ALTER TABLE dataset
    DROP CONSTRAINT FK_DATASET_ON_MODEL;
ALTER TABLE dataset
    ADD CONSTRAINT FK_DATASET_ON_MODEL FOREIGN KEY (model_id) REFERENCES model (id) ON DELETE CASCADE;
