name: Publish Docker image

on:
  release:
    types: [ published ]
  push:
    branches:
      - feat/JAQPOT-101/fix-sed

env:
  IMAGE_NAME: upcintua/jaqpot-api

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Update version in build.gradle.kts
        run: sed -i "s#{{VERSION_PLACEHOLDER}}#${{ steps.meta.outputs.version }}#g" build.gradle.kts

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build docker image
        run: ./gradlew bootBuildImage

      - name: Tag docker image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ steps.meta.outputs.tags }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image to DockerHub
        run: docker push ${{ steps.meta.outputs.tags }}
