name: Trigger Playwright Tests

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  workflow_dispatch:

jobs:
  trigger-e2e-tests:
    uses: ntua-unit-of-control-and-informatics/github-actions/.github/workflows/reusable_trigger_workflow.yml@main
    with:
      target_repo: ntua-unit-of-control-and-informatics/jaqpot-e2e-tests
      event_type: run_e2e_tests
    secrets:
      APP_ID: ${{ secrets.UPCI_NTUA_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.UPCI_NTUA_APP_SECRET }}
