name: Trigger Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.UPCI_NTUA_APP_ID }}
          private-key: ${{ secrets.UPCI_NTUA_APP_SECRET }}

      - name: Trigger tests in other repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ntua-unit-of-control-and-informatics/jaqpot-e2e-tests/dispatches \
            -d '{"event_type": "run_e2e_tests"}'
